version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Manager(4242)
       MYSQL_DATABASE: aigle
       MYSQL_USER: aigle_dbusr
       MYSQL_PASSWORD: Manager(4242)
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: aigle_dbusr
       WORDPRESS_DB_PASSWORD: Manager(4242)
       WORDPRESS_DB_NAME: aigle
volumes:
    db_data: {}
