version: '3.3'
services:
   db:
     image: 589589/wp:wpdb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     
   wordpress:
     depends_on:
       - db
     image: 589589/wp:custom
     ports:
       - "80:80"
     restart: always
     
volumes:
    db_data: {}
